[package]
name = "whatsapp_parser"
version = "0.1.0"
edition = "2021"

[lib]
name = "whatsapp_parser"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18.3", features = ["extension-module"] }
chrono = "0.4.24"
regex = "1.8.1"
serde = { version = "1.0.162", features = ["derive"] }
serde_json = "1.0.96"